## Displaying Matrix in Latex form

In [1]:
from IPython.display import display, Latex
import numpy as np

# This function converts the numpy array to a string to display as Latex
def matrix2string(m):
    import numpy as np
    assert isinstance(m, np.ndarray)
    text1 = '\\begin{bmatrix}'
    text3 = '\\end{bmatrix}'  
    def vec2string(v):
        text = "&".join([str(i) for i in v])
        return text   
    if len(m.shape)==1:
        text2 = vec2string(m)
        return text1 + text2 + text3  
    elif len(m.shape)==2:
        text2 = '\\\\'.join(vec2string(v) for v in m) + '\\\\ '
        return text1 + text2 + text3

def round_matrix(m, p):
    '''Rounds the matrix (A) to a given precesion (p)'''
    assert isinstance(p, int)
    assert p>=0
    assert isinstance(m, np.ndarray)
    m = np.int16(m) if np.all(np.int16(m)==m) else m.round(p)
    return m

def display_matrix(m):
    import numpy as np
    assert isinstance(m, np.ndarray)
    display(Latex(matrix2string(m)))

### Example - matrix

In [2]:
B = np.arange(9).reshape((3,3))
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
display_matrix(B)

<IPython.core.display.Latex object>

In [4]:
display(Latex('''\\begin{align} \\mathbf B = '''+matrix2string(B)+''' \\end{align}'''))


<IPython.core.display.Latex object>

### Example - row vector

In [5]:
r = np.arange(5).T
r

array([0, 1, 2, 3, 4])

In [6]:
display_matrix(r)

<IPython.core.display.Latex object>

In [7]:
display(Latex('''\\begin{align} \\mathbf r = '''+matrix2string(r)+''' \\end{align}'''))

<IPython.core.display.Latex object>

### Example - column vector

In [8]:
v = np.arange(3).reshape((3,1))
v

array([[0],
       [1],
       [2]])

In [9]:
display_matrix(v)

<IPython.core.display.Latex object>

In [10]:
display(Latex('''\\begin{align} \\mathbf v = '''+matrix2string(v)+''' \\end{align}'''))

<IPython.core.display.Latex object>

### Example - round vector

In [11]:
u = np.arange(3).reshape((3,1))/3
u

array([[0.        ],
       [0.33333333],
       [0.66666667]])

In [12]:
display_matrix(u)

<IPython.core.display.Latex object>

In [13]:
display_matrix(round_matrix(u, 2))

<IPython.core.display.Latex object>

In [14]:
# v vector originally consist of all integeres
display_matrix(round_matrix(v, 2))

<IPython.core.display.Latex object>